import type { GetServerSideProps, Metadata } from 'next'
import { Inter } from 'next/font/google'
import '../globals.css'
import Menu from './components/menu'
import { Separator } from "@/components/ui/separator";
import { parseCookies } from 'nookies';
import { redirect } from 'next/navigation';
import { cookies } from 'next/headers';

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'SCOSI | Dashboard',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {

  if(!verificaLogin()) {

    redirect('/');
  }

  return (
    <html lang="en">
      <body className={inter.className}>
        <Menu/>
        {children}
        <footer className='py-5 px-5 text-center text-slate-400'>Copyright © 2023 | By Állan Gomes</footer>
        </body>
    </html>
  )
}


export function verificaLogin() :boolean {
  // const {['scosi.token']:token} = parseCookies();
  const token = cookies().get('scosi.token');

  // console.log(token);

  if(!token)
    return false

  return true

}