import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import '../globals.css'
import Menu from './components/menu'
import { Separator } from "@/components/ui/separator";

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'SCOSI | Dashboard',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Menu/>
        {children}
        <footer className='py-5 px-5 text-center text-slate-400'>Copyright © 2023 | By Állan Gomes</footer>
        </body>
    </html>
  )
}
